name: cijepise
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  http: ^0.13.3
  intl: ^0.17.0
  toast: ^0.1.5
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.5
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  device_info: ^2.0.2
  flutter_local_notifications: ^5.0.0
  searchable_dropdown: ^1.1.3
  dropdown_search: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: UniSans
      fonts:
        - asset: assets/fonts/uni_sans_regular.ttf

  assets:
    - assets/images/
    - assets/icons/
    - lib/data/gradovi.json
